packages:
  # all packages in direct subdirs of packages/
  - 'packages/typescript'
  - 'packages/types'
  - 'packages/utils'
  - 'packages/core'
  - 'packages/tracing-internal'
  # - 'packages/replay-worker'
  # - 'packages/replay'
  - 'packages/integration-shims'
  - 'packages/browser'
  